### ISSUE TITLE
Error: Cannot find module 'li'

### ISSUE THREAD

**Issue by matjack1** [WP-API/node-wpapi#420]
Hello,

I'm trying v2 and I've encountered this error:

`Error: Cannot find module 'li'`

Manually adding the package fixes the issue. Maybe you want to add that in your requirements?

Happy to test it again or provide more info if needed.

**Comment by kadamwhite** [comment]
Hello, @matjack1 ! Can you clarify what version of the library you are using? I believe this should have been fixed as of #416, if you `npm install --save wpapi@1.2.1` it should pull in `li` as well.

**Comment by kadamwhite** [comment]
Ah, I misread your issue, you were asking about v2! Yes, that is fixed in `master` but we have not released a new alpha yet. I'll try to get one out later this week, but in the meantime your workaround makes sense.

As this is fixed in master, I'm going to close the issue.

**Comment by matjack1** [comment]
Thanks, sorry I didn't notice it was fixed in master :(

**Comment by kadamwhite** [comment]
No apology necessary, @matjack1 ; thank you very much for raising the issue when you encountered it! That's what makes open source work :)

**Comment by theabhinavdas** [comment]
This issue still isn't fixed :) Please reopen and fix. 

I had to manually install `li` as well via `npm i li`.
