### ISSUE TITLE
Is it just me or the error messages are awful?

### ISSUE THREAD

**Issue by dave-dm** [WP-API/node-wpapi#465]
For example, trying to post on a multisite that doesn't exist gives the error:

```
Not Found

      at Request.Object.<anonymous>.Request.callback (node_modules/superagent/lib/node/index.js:804:15)
      at IncomingMessage.parser (node_modules/superagent/lib/node/index.js:1036:18)
```

I've also gotten completely useless JSON.parse errors with no useful trace though I don't remember how to reproduce. I'm using Jest to catch and log errors, maybe it's parsing them wrong or something.

**Comment by marcofacheris** [comment]
Hi,

I am in a similar situation: I have an error but I don't know how to debug this because no further information is provided.

Error: Not Found
at Request.callback (/app/node_modules/wpapi/node_modules/superagent/lib/node/index.js:804:15)
at /app/node_modules/wpapi/node_modules/superagent/lib/node/index.js:1036:18

The file and line where the error is generated are the same.

**Comment by kadamwhite** [comment]
@countfak If you have an updated pagination snippet, could you share that as a docs PR (or respond with it here?) If we're sharing incorrect example code, we should fix that

**Comment by countfak** [comment]
Hi,

I'm not saying that the example code is wrong, it's been working fine but at some point it started to throw that error.
I still don't know why, maybe I changed something and it was my fault, sorry I don't remember.

This is how I fetch all posts now. This is working fine in my case and the error is gone.

```
let posts = [],
  postsBatch = [],
  page = 1;
do {
  try {
    postsBatch = await wp.posts().perPage(100).page(page);
  } catch (error) {
    console.error(error);
  }
  posts = posts.concat(postsBatch);
  page++;
} while (postsBatch && postsBatch._paging && page <= postsBatch._paging.totalPages);
console.log(posts);
```

**Comment by braniubojni** [comment]
Have same issue, in my case problem was with uploaded media, wordpress has limit 8mb for image.
